<?php

return [
    'icon-class' => [
        'arrow-left' => 'cil-arrow-left',
        'arrow-right' => 'cil-arrow-right',
        'check-alt' => 'check-alt',
        'x' => 'cil-x',
        'link' => 'cil-link',
        'search' => 'cil-search',
        'pen' => 'cil-pen',
        'reload' => 'cil-reload',
        'hand-point-up' => 'cil-hand-point-up',
        'save' => 'cil-save',
        'plus' => 'cil-plus',
        'trash' => 'cil-trash',
        'swap-vertical' => 'cil-swap-vertical',
        'cloud-download' => 'cil-cloud-download',
        'cloud-upload' => 'cil-cloud-upload',
        'description' => 'cil-description',
        'filter' => 'cil-filter',
        'folder' => 'cil-folder',
        'settings' => 'cil-settings',
        'menu' => 'cil-menu',
        'warning' => 'cil-warning',
        'phone' => 'cil-phone',
        'screen-desktop' => 'cil-screen-desktop',
        'screen-smartphone' => 'cil-screen-smartphone',
    ],
    'icon-text' => [
        'arrow-left' => '返回',
        'arrow-right' => '未定義',
        'check-alt' => '上線',
        'x' => '無效',
        'link' => '連結',
        'search' => '搜尋',
        'pen' => '編輯',
        'reload' => '重新整理',
        'hand-point-up' => '查看',
        'save' => '儲存',
        'plus' => '新增',
        'trash' => '刪除',
        'swap-vertical' => '排序',
        'cloud-download' => '下載',
        'cloud-upload' => '上傳',
        'description' => '描述',
        'filter' => '篩選',
        'folder' => '資料夾',
        'settings' => '設定',
        'menu' => '選單',
        'warning' => '警告',
        'phone' => '電話',
        'screen-desktop' => '桌機',
        'screen-smartphone' => '手機',
    ],
];
